"""initial

Revision ID: cd55451b1195
Revises: 
Create Date: 2023-12-12 22:04:43.561324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd55451b1195'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# performances = Table(
#     'performances',
#     metadata,
#     Column('id', Integer, primary_key=True),
#     Column('name', String(50)),
#     Column('price', Integer),
#     Column('begin_data', DateTime),
#     Column('begin_end', DateTime),
#     Column('plot', String(250)),
#     Column('genres', ARRAY(String)),
#     Column('description', String(250)),
#
# )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'performances',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('price', sa.Integer(), nullable=True),
        sa.Column('begin_data', sa.DateTime(), nullable=True),
        sa.Column('begin_end', sa.DateTime(), nullable=True),
        sa.Column('plot', sa.String(length=250), nullable=True),
        sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('description', sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'places_shows',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(50), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'shows',

        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=True),
        sa.Column('time_start', sa.DateTime(), nullable=True),
        sa.Column('busy', sa.Integer(), nullable=True),
        sa.Column('place_show_id', sa.Integer(), nullable=True),
        sa.Column('performances_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint('place_show_id'),
        sa.ForeignKeyConstraint('performances_id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performances')
    op.drop_table('places_shows')
    op.drop_table('shows')
    # ### end Alembic commands ###
